backend/build.gradle, backend/src/main/java/ssap/ssap/config/SwaggerConfig.java
Closes #9
Swagger 설정 추가로 API 문서화 구성
#9
=> feature: [BE] Swagger 적용 #9

backend/build.gradle, backend/src/main/java/ssap/ssap/config/ProxyConfig.java
Closes #10
환경 변수를 사용한 RestTemplate 프록시 설정 구성
#10
=> feature: [BE] Proxy 적용 #10

backend/build.gradle, backend/src/main/java/ssap/ssap/controller/OAuthController.java, backend/src/main/java/ssap/ssap/dto/Account.java, backend/src/main/java/ssap/ssap/dto/LoginResponseDto.java, backend/src/main/java/ssap/ssap/dto/OAuthDTO.java, backend/src/main/java/ssap/ssap/exception/GlobalExceptionHandler.java, backend/src/main/java/ssap/ssap/service/KakaoOAuthService.java, backend/src/main/java/ssap/ssap/service/OAuthService.java
- 카카오 로그인 API 연동
- 인가코드(code)를 받아, 유저 정보와, AccessToken&RefreshToken 발급 코드 구현
#6
=> feature: [BE] 카카오 로그인 기능 구현 #6

frontend/src/components/@common/Label/Label.stories.tsx, frontend/src/components/@common/Label/Label.tsx, frontend/src/styles/theme.ts
Label 컴퍼넌트 추가 및 secondary 컬러 변경하였습니다.
- Label 컴퍼넌트 추가
- secondary #FFFFFF로 컬러 변경
#32
=> Label 컴퍼넌트 추가 및 secondary 컬러 변경

backend/src/main/java/ssap/ssap/config/SwaggerConfig.java
Closes #37
OPenAPI에 기본 서버 주소를 설정하여 해결
OPenAPI에 기본 서버 주소를 설정하여 해결
#37
=> feature: [BE] Swagger에서 API 호출 시 CORS 에러 발생 #37

backend/src/main/java/ssap/ssap/config/SwaggerConfig.java
Closes #41
- security 스키마 적용
- security 스키마 적용
#41
=> fix: [BE] Swagger에서 로그아웃 API 요청 시 Authorization 값이 제대로 넘어가지 않는 문제 #41

backend/src/main/java/ssap/ssap/service/KakaoOAuthService.java
Closes #64
- 사용자 정보를 DB에 저장하는 메서드를 호출하지 않아 로그인이 성공했음에도 DB에 저장되지 않는 문제 해결
- 로그인 로직에서 예외 상황 처리 추가
- 로그 메시지 추가
- 로그인 성공 시 DB에 사용자 정보를 저장하는 메서드 호출 로직 추가
#64
=> fix: 최초 로그인 시 사용자 정보가 DB에 저장되지 않는 문제 #64

backend/src/main/java/ssap/ssap/domain/ErrandEntity.java, backend/src/main/java/ssap/ssap/dto/ErrandDTO.java, backend/src/main/java/ssap/ssap/service/ErrandService.java
Tasks Table 참조 필드 명 수정
Tasks Table 참조 필드 명 수정
=> refactor : 코드 수정

frontend/.eslintrc.js, frontend/package-lock.json, frontend/src/apis/errand.ts, frontend/src/components/@common/Input/Input.tsx, frontend/src/components/ErrandRequest/ErrandRequest.tsx, frontend/src/components/ErrandRequest/ImgFile/ImgFile.tsx, frontend/src/pages/ErrandRequest/ErrandRequestPage.tsx, frontend/src/types/errand.ts
요청서 작성 이미지 업로드 추가 및 오류 해결하였습니다.
- 이미지 파일 업로드 로직 추가 #88
- 요청서 작성 API 호출 추가 #92
#88 #92
=> 요청서 작성 이미지 업로드 및 API 호출 로직 추가

backend/src/main/java/ssap/ssap/controller/CategoryController.java, backend/src/main/java/ssap/ssap/controller/DetailedItemController.java, backend/src/main/java/ssap/ssap/controller/ErrandController.java, backend/src/main/java/ssap/ssap/controller/RequestController.java
Closes #96
CORS가 적용안된 Controller에 CORS 적용
- CategoryController, DetailedItemController, ErrandController, RequestController에 CORS 적용
#96
=> feature: CORS가 적용안된 Controller에 CORS 적용 #96

backend/src/main/java/ssap/ssap/dto/TaskRequestDto.java, backend/src/main/java/ssap/ssap/service/TaskService.java
Closes #100
심부름 요청서 작성 시 입력 값 수정
- detailedAddress 필수 -> 필수 X
- startTime 필수 -> 필수 X
- endTime 추가(필수 X)
- estimatedTime 제거
- auctionStartTime 필수 -> 필수 X
- auctionEndTime 필수 -> 필수 X
#100
=> feature: 심부름 요청서 작성 시 입력 값 수정 #100

backend/src/main/java/ssap/ssap/dto/TaskRequestDto.java
Closes #102
TaskRequestDto 클래스에서 fileData(심부름 게시글 첨부 사진 파일 URL) 제거
- TaskRequestDto 클래스에서 fileData(심부름 게시글 첨부 사진 파일 URL) 제거
#102
=> feature: TaskRequestDto(심부름 요청성 작성 API 호출 DTO) 수정 - fileData(심부름 게시글 첨부 사진 파일 URL) 제거

backend/src/main/java/ssap/ssap/controller/ErrandController.java
@CrossOrigin(origins = "*") 추가
@CrossOrigin(origins = "*") 추가
#97
=> ErrandController(메인페이지 실시간 심부름 리스트 API)에 CORS 적용

frontend/src/components/ErrandRequest/ErrandRequest.tsx, frontend/src/components/ErrandRequest/Timing/Timing.tsx, frontend/src/components/KakaoMap/KakaoMap.tsx, frontend/src/pages/ErrandRequest/ErrandRequestPage.tsx, frontend/src/types/errand.ts
심부름 요청서 제출 항목 수정과 카카오 지도 api 키 수정하였습니다.
- 심부름 요청서 제출 항목 수정
- 카카오 지도 api 키 수정
#118
=> 심부름 요청서 제출 항목 수정

backend/src/main/java/ssap/ssap/config/ProxyConfig.java, backend/src/main/java/ssap/ssap/controller/ErrandDetailedController.java, backend/src/main/java/ssap/ssap/dto/ErrandResponseDto.java, backend/src/main/java/ssap/ssap/service/ErrandDetailedService.java, backend/src/main/java/ssap/ssap/service/ErrandService.java
- ErrandDetailedService 추가
- ErrandDetailedController 추가
- ErrandService : taskId 추가
- ErrandDetailedService 추가
- ErrandDetailedController 추가
- ErrandService : taskId 추가
#5
=> feature : 심부름 상세 페이지 추가 작업

backend/build.gradle, backend/src/main/java/ssap/ssap/controller/UserController.java, backend/src/main/java/ssap/ssap/exception/GlobalExceptionHandler.java, backend/src/main/java/ssap/ssap/exception/InvalidAccessTokenException.java, backend/src/main/java/ssap/ssap/service/KakaoOAuthService.java, backend/src/main/java/ssap/ssap/service/UserService.java
Closes #71
- 사용자 정보 조회 API 구현
- 사용자 정보 조회 API 추가
- 엑세스 토큰 검증 오류에 대한 예외처리 로직 수정
#71
=> feature: 사용자 정보 조회 API 구현 #71

backend/src/main/java/ssap/ssap/dto/DetailedItemDTO.java, backend/src/main/java/ssap/ssap/dto/ErrandResponseDto.java, backend/src/main/java/ssap/ssap/service/ErrandService.java
itemid → id 수정
detailedItemName → categoryName 수정
itemid → id 수정
detailedItemName → categoryName 수정
#130
=> refactor : DetailedItemDTO 수정 #130

backend/src/main/java/ssap/ssap/controller/DetailedItemController.java, backend/src/main/java/ssap/ssap/controller/ErrandController.java, backend/src/main/java/ssap/ssap/controller/ErrandDetailedController.java
토큰 검증 중 오류가 발생했습니다. → 요청을 처리하는 중에 서버에서 오류가 발생했습니다.
토큰 검증 중 오류가 발생했습니다. → 요청을 처리하는 중에 서버에서 오류가 발생했습니다.
#132
=> 메인페이지 카테고리, 심부름 리스트 에러 로그 수정

backend/src/main/java/ssap/ssap/service/ErrandDetailedService.java
"detail item" → "detailitem" 띄어쓰기 수정
"detail item" → "detailitem" 띄어쓰기 수정
#135
=> 심부름 상세 페이지 ErrandDetailedService 수정

backend/src/main/java/ssap/ssap/controller/BidController.java, backend/src/main/java/ssap/ssap/domain/Auction.java, backend/src/main/java/ssap/ssap/domain/Bid.java, backend/src/main/java/ssap/ssap/dto/BidRequestDto.java, backend/src/main/java/ssap/ssap/repository/AuctionRepository.java, backend/src/main/java/ssap/ssap/repository/BidRepository.java, backend/src/main/java/ssap/ssap/service/BidService.java, backend/src/main/java/ssap/ssap/service/TaskService.java
Closes #139
심부름 입찰 API 및 서비스 로직 구현 
- 심부름 입찰 API 구현
- 심부름 입찰 서비스 로직 구현
- DB연동 작업
#139
=> feature: 심부름 입찰 API 및 서비스 로직 구현 #139

backend/src/main/java/ssap/ssap/service/TaskService.java
Closes #145
- Task 엔티티 저장 로직 순서 개선
- Task 엔티티 저장 로직 순서 개선
#145
=> refactor: [BE] Task 엔티티 저장 로직 순서 개선 #145

backend/src/main/java/ssap/ssap/domain/Task.java, backend/src/main/java/ssap/ssap/service/ErrandDetailedService.java
Task 엔티티에 auction 연관성 추가
Service - auction_id 추가
Task 엔티티에 auction 연관성 추가
Service - auction_id 추가
#147
=> 심부름 상세 페이지 Task 엔티티 연관성 추가 및 service 수정

backend/src/main/java/ssap/ssap/service/ErrandDetailedService.java
메인페이지 심부름 상세 페이지 AuctionId 참조 수정
테이블 Task 에서 Auction으로 수정
=> 메인페이지 심부름 상세 페이지 AuctionId 참조 수정

backend/src/main/java/ssap/ssap/controller/BidController.java, backend/src/main/java/ssap/ssap/controller/BidResponseDto.java, backend/src/main/java/ssap/ssap/repository/BidRepository.java, backend/src/main/java/ssap/ssap/service/BidService.java
Closes #149
- 특정 경매의 최신 입찰 정보를 조회 API 구현
- 특정 경매의 최신 입찰 정보를 조회 서비스 로직 및 DB연동 구현
- 특정 경매의 최신 입찰 정보를 조회 API 구현
- 특정 경매의 최신 입찰 정보를 조회 서비스 로직 및 DB연동 구현
=> feature: 특정 경매의 최신 입찰 정보를 조회 API 구현 #149

frontend/src/components/ErrandRequest/DateInput/DateInput.tsx
요청서 작성하기 날짜/시간 선택 input이 모바일 환경에서 키보드가 올라와서 설정하기 어려움.. 있습니다.
커스텀해서 버튼으로 변경하였습니다.
#158
=> 요청서 작성하기 날짜/시간 선택 input에서 버튼으로 변경

backend/src/main/java/ssap/ssap/controller/ErrandListController.java, backend/src/main/java/ssap/ssap/repository/TaskRepository.java, backend/src/main/java/ssap/ssap/service/ErrandListService.java
카테고리 별 심부름 리스트 조회 기능 구현
카테고리 별 심부름 리스트 조회 기능 구현
#137
=> 카테고리 별 심부름 리스트 조회 기능 구현

backend/src/main/java/ssap/ssap/controller/ErrandListController.java, backend/src/main/java/ssap/ssap/repository/TaskRepository.java, backend/src/main/java/ssap/ssap/service/ErrandListService.java
카테고리 별 심부름 리스트 '동'(지번) 필터링 기능 구현
카테고리 별 심부름 리스트 '동'(지번) 필터링 기능 구현
#165
=> 카테고리 별 심부름 리스트 '동'(지번) 필터링 기능 구현

backend/src/main/java/ssap/ssap/controller/ErrandController.java, backend/src/main/java/ssap/ssap/repository/TaskRepository.java, backend/src/main/java/ssap/ssap/service/ErrandService.java
메인페이지 🌈 우리 동네 심부름 리스트 동(지번) 별 필터링 구현
메인페이지 🌈 우리 동네 심부름 리스트 동(지번) 별 필터링 구현
#171
=> 메인페이지 🌈 우리 동네 심부름 리스트 동(지번) 별 필터링 구현 #171

backend/src/main/java/ssap/ssap/service/ErrandService.java
Closes #176
- 주소 추출 메소드를 '동'에서 '구'로 변경
- 주소 추출 메소드를 '동'에서 '구'로 변경
#176
=> feature: 메인페이지 🌈 우리 동네 심부름 리스트 필터링 방식 수정 (동 -> 구 기준으로 수정) #176

backend/src/main/java/ssap/ssap/service/BidService.java
Closes #200
- 입찰 금액 검증 로직 개선 및 관련 로그 추가
- 입찰 금액 검증 로직 개선 및 관련 로그 추가
#200
=> fix: 최초 입찰 시 입찰 가격 비교 대상이 없어 입찰이 되지 않는 문제 #200

frontend/src/components/bottomSheet/BottomSheet.tsx, frontend/src/components/bottomSheet/Content.tsx, frontend/src/pages/ErrandDetails/ErrandDetailsPage.tsx
Hotfix 입찰하기 바텀시트 현재 입찰가 0으로 초기화 되는 버그 수정
- 상태를 하위 컴포넌트로 이동시키고,
- useState(0)이 아닌, useState(auctionData.amount)로 변경하였습니다.
- 또한 한국 원화처럼 보이게 수정 하였습니다.
=> [FE] Hotfix 입찰하기 바텀시트 현재 입찰가 0으로 초기화 되는 버그 수정

frontend/src/components/@common/Button/Button.tsx, frontend/src/components/@common/Footer/Footer.tsx, frontend/src/components/ErrandDetail/ErrandDetail.tsx, frontend/src/components/ErrandDetail/ErrandFeeContainer.tsx, frontend/src/components/ErrandDetail/KakaoMap.tsx, frontend/src/components/ErrandDetail/UserProfile.tsx, frontend/src/components/ErrandList/ErrandItem.tsx, frontend/src/components/ErrandList/Nav.tsx, frontend/src/components/ErrandList/NavBar.tsx, frontend/src/components/Loading/Loding.tsx, frontend/src/components/Main/Errands.tsx, frontend/src/components/Main/Main.tsx, frontend/src/components/Template.tsx, frontend/src/hooks/useLockBodyScroll.ts, frontend/src/pages/ErrandDetails/ErrandDetailsPage.tsx, frontend/src/pages/ErrandList/ErrandListPage.tsx, frontend/src/pages/ErrandRequest/ErrandRequestPage.tsx, frontend/src/pages/Home/HomePage.tsx, frontend/src/pages/Login/LoginPage.tsx
각 페이지 및 컴포넌트별 스타일의 일관성 및 시각적 개선하였습니다.
=> design(전체 페이지 CSS 디자인 오버홀): #197

frontend/src/components/ErrandDetail/UserProfile.tsx, frontend/src/components/bottomSheet/Content.tsx, frontend/src/pages/ErrandDetails/ErrandDetailsPage.tsx
Hotfix #204 입찰 바텀시트 유저 성뱔과 나이대 표기 방법 수정
=> Hotfix #204 입찰 바텀시트 유저 성뱔과 나이대 표기 방법 수정 

frontend/src/components/ErrandDetail/ErrandDate.tsx
=> fix: startTime을 StartTime으로 변경
